// Extracts data embedded by pdf-export.js (the regular card) or
// acbl-export.js (the ACBL card) from an uploaded PDF — both use the same
// hidden-text marker technique, just with a different marker string, so the
// PDF-parsing/marker-scanning logic lives here once and each caller just
// supplies its own marker and not-found message.
//
// Uses the vendored PDF.js legacy UMD build (loaded as a plain global via
// <script src="vendor/pdf.min.js">, same pattern as html2pdf.bundle.min.js)
// rather than a modern ES-module build — that avoids needing dynamic
// import() / <script type="module"> (which have their own MIME-type and
// module-scoping gotchas on some static hosts) for a feature this small.

const PDF_WORKER_SRC = "vendor/pdf.worker.min.js";
pdfjsLib.GlobalWorkerOptions.workerSrc = PDF_WORKER_SRC;

function withTimeout(promise, ms, message) {
  return Promise.race([
    promise,
    new Promise((_, reject) => setTimeout(() => reject(new Error(message)), ms))
  ]);
}

async function extractMarkedDataFromPdf(file, marker, notFoundMessage) {
  let doc;
  try {
    const buffer = await file.arrayBuffer();
    doc = await withTimeout(
      pdfjsLib.getDocument({ data: buffer }).promise,
      20000,
      "Timed out reading that PDF. It may be corrupted, or your browser may not support reading it — try a different browser if this keeps happening."
    );
  } catch (err) {
    throw new Error("Couldn't read that file as a PDF: " + err.message);
  }

  let fullText = "";
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();
    fullText += content.items.map(item => item.str).join("");
  }

  // The marker + payload is written as a single long text run (see
  // pdf-export.js / acbl-export.js), but PDF text-layer reconstruction can
  // still insert stray whitespace when joining text items back together —
  // and neither the marker nor base64 ever legitimately contain whitespace,
  // so stripping all of it first is always safe and guards against a single
  // inserted space silently truncating the match below.
  const cleaned = fullText.replace(/\s+/g, "");

  const markerIndex = cleaned.indexOf(marker);
  if (markerIndex === -1) {
    // Diagnostic detail appended so a report of this error is actionable
    // without needing browser dev tools: how much text actually came back,
    // and whether the OTHER marker (regular card vs ACBL card) was found
    // instead, which would mean the wrong upload button was used.
    const otherMarker = marker === DATA_MARKER ? ACBL_DATA_MARKER : DATA_MARKER;
    const foundOther = cleaned.indexOf(otherMarker) !== -1;
    const snippet = cleaned.slice(0, 80);
    throw new Error(
      notFoundMessage +
      `\n\n[diagnostic] pages: ${doc.numPages}, extracted chars: ${cleaned.length}` +
      (foundOther ? ", found the OTHER file type's marker instead (wrong upload button?)" : "") +
      (cleaned.length ? `, starts with: "${snippet}"` : ", no text was extracted at all")
    );
  }

  const match = cleaned.slice(markerIndex + marker.length).match(/^[A-Za-z0-9+/=]+/);
  if (!match) {
    throw new Error("This PDF's embedded data looks corrupted.");
  }

  try {
    return JSON.parse(decodeURIComponent(escape(atob(match[0]))));
  } catch (err) {
    throw new Error("This PDF's embedded data could not be read: " + err.message);
  }
}

function extractConfigFromPdf(file) {
  return extractMarkedDataFromPdf(file, DATA_MARKER,
    "This PDF doesn't contain card data — please upload a PDF that was exported from this tool, or start a new card instead.");
}

function extractAcblConfigFromPdf(file) {
  return extractMarkedDataFromPdf(file, ACBL_DATA_MARKER,
    "This PDF doesn't contain ACBL card data — please upload an ACBL card PDF that was generated by this tool (via \"Create ACBL Card\" or \"Edit ACBL Card\").");
}
